### ISSUE TITLE
Metadata values of `""` should not blow up

### ISSUE THREAD

**Issue by litch** [obsidian-btc/event-store-messaging#7]
When an EventStore message gets written without metadata explicitly, then read back out, the value of the metadata attribute is `""`.

This causes this library to blow up:

```
[2015-10-22T19:57:12.877-04:00] SetAttributes TRACE: Building (Receiver: #<EventStore::Messaging::Message::Metadata:0x007f9185ef5dd0>)
ArgumentError:  can't be used to set attributes. It can't be converted to Hash.
	from /Users/litch/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/set_attributes-0.1.0/lib/set_attributes/set_attributes.rb:21:in `build'
	from /Users/litch/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/set_attributes-0.1.0/lib/set_attributes/set_attributes.rb:36:in `call'
	from /Users/litch/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/schema-0.1.0/lib/schema/data_structure.rb:20:in `set_attributes'
	from /Users/litch/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/schema-0.1.0/lib/schema/data_structure.rb:14:in `block in build'
	from /Users/litch/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/schema-0.1.0/lib/schema/data_structure.rb:13:in `tap'
	from /Users/litch/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/schema-0.1.0/lib/schema/data_structure.rb:13:in `build'
	from /Users/litch/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/event_store-messaging-0.1.0/lib/event_store/messaging/message/metadata.rb:18:in `build'
	from /Users/litch/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/event_store-messaging-0.1.0/lib/event_store/messaging/message/import/event_data.rb:15:in `call'
	from /Users/litch/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/event_store-messaging-0.1.0/lib/event_store/messaging/dispatcher.rb:76:in `build_message'
	from /Users/litch/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/event_store-entity_projection-0.1.0/lib/event_store/entity_projection/entity_projection.rb:93:in `build_message'
	from /Users/litch/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/event_store-messaging-0.1.0/lib/event_store/messaging/message_reader.rb:69:in `dispatch'
	from /Users/litch/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/event_store-messaging-0.1.0/lib/event_store/messaging/message_reader.rb:58:in `dispatch_event_data'
	from /Users/litch/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/event_store-messaging-0.1.0/lib/event_store/messaging/message_reader.rb:50:in `block in start'
	from /Users/litch/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/event_store-client-http-0.1.1/lib/event_store/client/http/event_reader.rb:60:in `call'
	from /Users/litch/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/event_store-client-http-0.1.1/lib/event_store/client/http/event_reader.rb:60:in `block in read_slice'
	from /Users/litch/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/event_store-client-http-0.1.1/lib/event_store/client/http/slice.rb:47:in `call'
... 13 levels...
	from /Users/litch/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/event_store-client-http-0.1.1/lib/event_store/client/http/stream_reader/terminal.rb:7:in `each'
	from /Users/litch/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/event_store-client-http-0.1.1/lib/event_store/client/http/event_reader.rb:52:in `each_slice'
	from /Users/litch/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/event_store-client-http-0.1.1/lib/event_store/client/http/event_reader.rb:45:in `each'
	from /Users/litch/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/event_store-messaging-0.1.0/lib/event_store/messaging/message_reader.rb:49:in `start'
	from /Users/litch/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/event_store-entity_projection-0.1.0/lib/event_store/entity_projection/entity_projection.rb:82:in `call'
	from /Users/litch/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/event_store-entity_projection-0.1.0/lib/event_store/entity_projection/entity_projection.rb:70:in `call'
```

This is problematic.

We have attempted to alleviate this issue using refinements, but during the investigaton on how to do that, found that actually, there are several layers of `nil` protection for metadata.

https://github.com/obsidian-btc/event-store-messaging/blob/af4b03e6f761001722c7779dd962e04a73bb7e35/lib/event_store/messaging/message.rb#L56

So this library seems to have been built explicitly to tolerate "no" metadata, but there was a mistake in implementation that causes the "no" metadata case in real life to be misinterpreted.

**Comment by litch** [comment]
Thank you for fixing this at a lower layer @sbellware
