### ISSUE TITLE
The tests on this library should be executable.

### ISSUE THREAD

**Issue by litch** [obsidian-btc/event-store-messaging#8]
I pulled this repo, bundled, and get this.

```
% LOG_LEVEL=info ruby test/spec.rb
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
/Users/litch/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/event_store-client-http-0.1.1/lib/event_store/client/http/controls.rb:1:in `require': cannot load such file -- controls (LoadError)
	from /Users/litch/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/event_store-client-http-0.1.1/lib/event_store/client/http/controls.rb:1:in `<top (required)>'
	from /Users/litch/code/obsidian/event-store-messaging/lib/event_store/messaging/controls.rb:1:in `require'
	from /Users/litch/code/obsidian/event-store-messaging/lib/event_store/messaging/controls.rb:1:in `<top (required)>'
	from /Users/litch/code/obsidian/event-store-messaging/test/test_init.rb:11:in `require'
	from /Users/litch/code/obsidian/event-store-messaging/test/test_init.rb:11:in `<top (required)>'
	from test/spec.rb:1:in `require_relative'
	from test/spec.rb:1:in `<main>'
```

I added `controls` to the `Gemfile`, and bundled, but got a new error.

```
% LOG_LEVEL=info ruby test/spec.rb
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
/Users/litch/code/obsidian/event-store-messaging/lib/event_store/messaging/controls/message.rb:46:in `time': uninitialized constant Controls::Time (NameError)
	from /Users/litch/code/obsidian/event-store-messaging/lib/event_store/messaging/controls/message.rb:57:in `example'
	from /Users/litch/code/obsidian/event-store-messaging/test/spec/client_integration/expected_version.rb:7:in `block in <top (required)>'
	from /Users/litch/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.5.1/lib/minitest/spec.rb:69:in `class_eval'
	from /Users/litch/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.5.1/lib/minitest/spec.rb:69:in `describe'
	from /Users/litch/code/obsidian/event-store-messaging/test/spec/client_integration/expected_version.rb:3:in `<top (required)>'
	from /Users/litch/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/runner-0.1.0/lib/runner/runner.rb:56:in `load'
	from /Users/litch/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/runner-0.1.0/lib/runner/runner.rb:56:in `block in call'
	from /Users/litch/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/runner-0.1.0/lib/runner/runner.rb:55:in `each'
	from /Users/litch/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/runner-0.1.0/lib/runner/runner.rb:55:in `call'
	from /Users/litch/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/runner-0.1.0/lib/runner/runner.rb:33:in `call'
	from test/spec.rb:3:in `<main>'
```

I give up.

**Comment by litch** [comment]
@sbellware added the controls library to the Gemfile, alleviating the first part of this issue.

The second was caused by the wrong ruby version being used.  One of the dependencies of this library requires ruby 2.2.3.  However, this one does not, explicitly, and so the gem can be built with ruby 2.2.2, though it is not functional.
